package com.epam.pizzeria.util.constants;

public class ParameterNamesConstants {
    public static final String LOCALE = "locale";
    public static final String SELECTED_LOCALE = "selectedLocale";
    public static final String LOCALE_ID = "localeId";
    public static final String LOCALES = "locales";
    public static final String USERS = "users";
    public static final String USER_ID_FOR_ADMIN = "userIdForAdmin";
    public static final String USER_DATA_FOR_ADMIN = "userDataForAdmin";
    public static final String USER = "user";
    public static final String EMAIL = "email";
    public static final String USER_ID = "userId";
    public static final String PASSWORD = "password";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String BIRTHDAY = "birthday";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String ADDRESS = "address";
    public static final String IS_ADMIN = "isAdmin";
    public static final String IS_BANNED = "isBanned";
    public static final String PRODUCT = "product";
    public static final String PRODUCTS = "products";
    public static final String PRODUCT_ID = "productId";
    public static final String PRODUCT_NAME = "productName";
    public static final String PRODUCT_DESCRIPTION = "description";
    public static final String PRODUCT_COST = "cost";
    public static final String PRODUCT_COUNT = "count";
    public static final String COUNTRY_ID = "countryId";
    public static final String CATEGORY_ID = "categoryId";
    public static final String TOTAL_COST = "totalCost";
    public static final String PRODUCTS_FROM_BASKET = "productsFromBasket";
    public static final String PRODUCTS_FROM_BASKET_BY_USER_ID = "productsFromBasketByUserId";
    public static final String COUNTRIES = "countries";
    public static final String CATEGORIES = "categories";
    public static final String CATEGORY_NAME = "categoryName";
    public static final String CATEGORY_PARENT_ID = "parentId";
    public static final String LOCALE_SHORT_NAME = "localeShortName";
    public static final String STATUS_ID = "statusId";
    public static final String STATUS_LOCALE_LIST = "statusLocaleList";
    public static final String ORDER_ID = "orderId";
    public static final String ORDERS = "orders";
}
